[package]
name = "pkmnfusion"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
bevy_ecs_tilemap = "0.18"

# Faster debug builds â€” critical for Bevy
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
